- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ['~']

- shell:
    - [zsh ~/.dotfiles/scripts/install_dependencies, Installing dependencies]
    - [curl -sL git.io/antibody | sudo sh -s - -b /usr/local/bin, Installing Antibody]
    - [antibody bundle <~/.dotfiles/zsh/plugins.txt >~/.zsh_plugins.sh, Install plugin bundle]

- link:
    ~/.zshrc: zsh/.zshrc
    ~/.gitconfig: home/.gitconfig
    ~/.gitignore_global: home/.gitignore_global
    ~/.hyper.js: home/.hyper.js
