- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ['~']

- shell:
    - [./scripts/install_dependencies, Installing dependencies]
    - [curl -sL git.io/antibody | sh -s, Installing Antibody]
    - [antibody bundle <~/.dotfiles/zsh/plugins.txt >~/.zsh_plugins.sh, Install plugin bundle]

- link:
    ~/.zshrc: zsh/zshrc
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/gitignore_global
