# First remove *all* keybindings
#unbind-key -a
unbind '"'
unbind %
unbind p
unbind n
unbind Up
unbind Down
unbind Left
unbind Right
unbind M-Up
unbind M-Down
unbind M-Left
unbind M-Right
unbind S-Up
unbind S-Down
unbind S-Left
unbind S-Right
unbind C-Up
unbind C-Down
unbind C-Left
unbind C-Right

bind C-x lock-server
bind C-c new-window -c "$HOME"
bind C-d detach
bind r command-prompt "rename-window %%"
bind R source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"
bind C-r refresh-client
bind C-l send-keys C-l

bind C-a last-window
bind C-w list-windows
bind C-p previous-window
bind C-n next-window

bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

bind -r , resize-pane -L 20
bind -r . resize-pane -R 20
bind -r - resize-pane -D 5
bind -r = resize-pane -U 5
bind z resize-pane -Z

bind : command-prompt
bind * setw synchronize-panes
bind P set pane-border-status
bind c kill-pane
bind x swap-pane -D
bind S choose-session

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel

bind -n Home send Escape "OH"
bind -n End send Escape "OF"

# don't yank mouse selection on release; instead use alt+w
# or ctrl+shift+c
# https://mwolson.org/blog/2025-11-12-ghostty-tmux-uniform-copy-paste/
unbind -T copy-mode MouseDragEnd1Pane
unbind -T copy-mode MouseDown1Pane
bind-key -T root DoubleClick1Pane select-pane -t = \; \
  if-shell -F "#{||:#{pane_in_mode},#{mouse_any_flag}}" { \
    send-keys -M \
  } { \
    copy-mode -H ; \
    send-keys -X select-word \
  }
bind-key -T root TripleClick1Pane select-pane -t = \; \
  if-shell -F "#{||:#{pane_in_mode},#{mouse_any_flag}}" { \
    send-keys -M \
  } { \
    copy-mode -H ; \
    send-keys -X select-line \
  }
bind -T copy-mode MouseDown1Pane select-pane \; send-keys -X clear-selection
bind -T copy-mode DoubleClick1Pane select-pane \; send-keys -X select-word
bind -T copy-mode TripleClick1Pane select-pane \; send-keys -X select-line
bind -T copy-mode C-S-c send-keys -X copy-pipe
bind -T copy-mode R send-keys -X refresh-from-pane
bind -T copy-mode r send-keys -X rectangle-toggle
