# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]

# These take precedence over the default keymap.
prepend_keymap = [
  { on = "?", run = "help", desc = "Open help" },
]

# These are appended to the default keymap.
append_keymap = [
  { on = [ "g", "t" ], run = "cd /tmp", desc = "Go /tmp" },
]
